name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: |
          cd server
          ./gradlew build

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: goodfarmserver.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd server
          docker build --platform linux/amd64 -t goodfarmserver.azurecr.io/goodfarmserver:latest .
          docker push goodfarmserver.azurecr.io/goodfarmserver:latest

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az containerapp update --name goodfarm-server --resource-group rg-team-garlic --image goodfarmserver.azurecr.io/goodfarmserver:latest
